using System.Collections.Generic;

namespace TongFang
{
    public static class Layouts
    {
        public static readonly Dictionary<Key, (byte Row, byte Column)> IsoCoords = new Dictionary<Key, (byte Row, byte Column)>
        {
            [Key.LEFT_CONTROL] = (0, 0),
            [Key.FN_Key] = (0, 2),
            [Key.LEFT_WINDOWS] = (0, 3),
            [Key.LEFT_ALT] = (0, 4),
            [Key.SPACE] = (0, 7),
            [Key.RIGHT_ALT] = (0, 10),
            [Key.MENU] = (0, 11),
            [Key.RIGHT_CONTROL] = (0, 12),
            [Key.ARROW_LEFT] = (0, 13),
            [Key.DOWN_ARROW] = (0, 14),
            [Key.RIGHT_ARROW] = (0, 15),
            [Key.NUMPAD_0] = (0, 16),
            [Key.NUMPAD_PERIOD] = (0, 17),

            [Key.LEFT_SHIFT] = (1, 0),
            [Key.BACKSLASH_UK] = (1, 2),
            [Key.Z] = (1, 3),
            [Key.X] = (1, 4),
            [Key.C] = (1, 5),
            [Key.V] = (1, 6),
            [Key.B] = (1, 7),
            [Key.N] = (1, 8),
            [Key.M] = (1, 9),
            [Key.COMMA] = (1, 10),
            [Key.PERIOD] = (1, 11),
            [Key.FORWARD_SLASH] = (1, 12),
            [Key.RIGHT_SHIFT] = (1, 13),
            [Key.UP_ARROW] = (1, 14),
            [Key.NUMPAD_ONE] = (1, 15),
            [Key.NUMPAD_TWO] = (1, 16),
            [Key.NUMPAD_THREE] = (1, 17),
            [Key.NUMPAD_ENTER] = (1, 18),

            [Key.CAPS_LOCK] = (2, 0),
            [Key.A] = (2, 2),
            [Key.S] = (2, 3),
            [Key.D] = (2, 4),
            [Key.F] = (2, 5),
            [Key.G] = (2, 6),
            [Key.H] = (2, 7),
            [Key.J] = (2, 8),
            [Key.K] = (2, 9),
            [Key.L] = (2, 10),
            [Key.SEMICOLON] = (2, 11),
            [Key.APOSTROPHE] = (2, 12),
            [Key.HASHTAG] = (2, 13),
            [Key.NUMPAD_FOUR] = (2, 15),
            [Key.NUMPAD_FIVE] = (2, 16),
            [Key.NUMPAD_SIX] = (2, 17),

            [Key.TAB] = (3, 0),
            [Key.Q] = (3, 2),
            [Key.W] = (3, 3),
            [Key.E] = (3, 4),
            [Key.R] = (3, 5),
            [Key.T] = (3, 6),
            [Key.Y] = (3, 7),
            [Key.U] = (3, 8),
            [Key.I] = (3, 9),
            [Key.O] = (3, 10),
            [Key.P] = (3, 11),
            [Key.OPEN_BRACKET] = (3, 12),
            [Key.CLOSE_BRACKET] = (3, 13),
            [Key.ENTER] = (3, 14),
            [Key.NUMPAD_SEVEN] = (3, 15),
            [Key.NUMPAD_EIGHT] = (3, 16),
            [Key.NUMPAD_NINE] = (3, 17),
            [Key.NUMPAD_PLUS] = (3, 18),

            [Key.TILDE] = (4, 0),
            [Key.ONE] = (4, 1),
            [Key.TWO] = (4, 2),
            [Key.THREE] = (4, 3),
            [Key.FOUR] = (4, 4),
            [Key.FIVE] = (4, 5),
            [Key.SIX] = (4, 6),
            [Key.SEVEN] = (4, 7),
            [Key.EIGHT] = (4, 8),
            [Key.NINE] = (4, 9),
            [Key.ZERO] = (4, 10),
            [Key.MINUS] = (4, 11),
            [Key.EQUALS] = (4, 12),
            [Key.BACKSPACE] = (4, 14),
            [Key.NUMLOCK] = (4, 15),
            [Key.NUMPAD_DIVIDE] = (4, 16),
            [Key.NUMPAD_MULTIPLY] = (4, 17),
            [Key.NUMPAD_MINUS] = (4, 18),

            [Key.ESCAPE] = (5, 0),
            [Key.F1] = (5, 1),
            [Key.F2] = (5, 2),
            [Key.F3] = (5, 3),
            [Key.F4] = (5, 4),
            [Key.F5] = (5, 5),
            [Key.F6] = (5, 6),
            [Key.F7] = (5, 7),
            [Key.F8] = (5, 8),
            [Key.F9] = (5, 9),
            [Key.F10] = (5, 10),
            [Key.F11] = (5, 11),
            [Key.F12] = (5, 12),
            [Key.INSERT] = (5, 13),
            [Key.DELETE] = (5, 14),
            [Key.HOME] = (5, 15),
            [Key.END] = (5, 16),
            [Key.PAGE_UP] = (5, 17),
            [Key.PAGE_DOWN] = (5, 18)
        };

        public static readonly Dictionary<Key, (byte Row, byte Column)> AnsiCoords = new Dictionary<Key, (byte Row, byte Column)>
        {
            [Key.LEFT_CONTROL] = (0, 0),
            [Key.FN_Key] = (0, 1),
            [Key.LEFT_WINDOWS] = (0, 3),
            [Key.LEFT_ALT] = (0, 4),
            [Key.SPACE] = (0, 7),
            [Key.RIGHT_ALT] = (0, 10),
            [Key.MENU] = (0, 11),
            [Key.RIGHT_CONTROL] = (0, 12),
            [Key.ARROW_LEFT] = (0, 13),
            [Key.DOWN_ARROW] = (0, 14),
            [Key.RIGHT_ARROW] = (0, 15),

            [Key.LEFT_SHIFT] = (1, 1),
            [Key.Z] = (1, 3),
            [Key.X] = (1, 4),
            [Key.C] = (1, 5),
            [Key.V] = (1, 6),
            [Key.B] = (1, 7),
            [Key.N] = (1, 8),
            [Key.M] = (1, 9),
            [Key.COMMA] = (1, 10),
            [Key.PERIOD] = (1, 11),
            [Key.FORWARD_SLASH] = (1, 12),
            [Key.RIGHT_SHIFT] = (1, 13),
            [Key.UP_ARROW] = (1, 14),
            [Key.END] = (1, 15),

            [Key.CAPS_LOCK] = (2, 0),
            [Key.A] = (2, 2),
            [Key.S] = (2, 3),
            [Key.D] = (2, 4),
            [Key.F] = (2, 5),
            [Key.G] = (2, 6),
            [Key.H] = (2, 7),
            [Key.J] = (2, 8),
            [Key.K] = (2, 9),
            [Key.L] = (2, 10),
            [Key.SEMICOLON] = (2, 11),
            [Key.APOSTROPHE] = (2, 12),
            [Key.ENTER] = (2, 14),
            [Key.PAGE_DOWN] = (2, 15),

            [Key.TAB] = (3, 0),
            [Key.Q] = (3, 2),
            [Key.W] = (3, 3),
            [Key.E] = (3, 4),
            [Key.R] = (3, 5),
            [Key.T] = (3, 6),
            [Key.Y] = (3, 7),
            [Key.U] = (3, 8),
            [Key.I] = (3, 9),
            [Key.O] = (3, 10),
            [Key.P] = (3, 11),
            [Key.OPEN_BRACKET] = (3, 12),
            [Key.CLOSE_BRACKET] = (3, 13),
            [Key.BACKSLASH] = (3, 14),
            [Key.PAGE_UP] = (3, 15),

            [Key.TILDE] = (4, 0),
            [Key.ONE] = (4, 1),
            [Key.TWO] = (4, 2),
            [Key.THREE] = (4, 3),
            [Key.FOUR] = (4, 4),
            [Key.FIVE] = (4, 5),
            [Key.SIX] = (4, 6),
            [Key.SEVEN] = (4, 7),
            [Key.EIGHT] = (4, 8),
            [Key.NINE] = (4, 9),
            [Key.ZERO] = (4, 10),
            [Key.MINUS] = (4, 11),
            [Key.EQUALS] = (4, 12),
            [Key.BACKSPACE] = (4, 14),
            [Key.HOME] = (4, 15),

            [Key.ESCAPE] = (5, 0),
            [Key.F1] = (5, 1),
            [Key.F2] = (5, 2),
            [Key.F3] = (5, 3),
            [Key.F4] = (5, 4),
            [Key.F5] = (5, 5),
            [Key.F6] = (5, 6),
            [Key.F7] = (5, 7),
            [Key.F8] = (5, 8),
            [Key.F9] = (5, 9),
            [Key.F10] = (5, 10),
            [Key.F11] = (5, 11),
            [Key.F12] = (5, 12),
            [Key.INSERT] = (5, 13),
            [Key.PRINT_SCREEN] = (5, 14),
            [Key.DELETE] = (5, 15),
        };
    }
}
