using RGB.NET.Core;
using TongFang;
using System.Collections.Generic;

namespace TongfangLedMapping
{
    public static class TongfangLedMapping
    {
        public static Dictionary<TongFang.Key, LedId> Mapping { get; } = new()
        {
            [TongFang.Key.ESCAPE] = LedId.Keyboard_Escape,
            [TongFang.Key.TILDE] = LedId.Keyboard_GraveAccentAndTilde,
            [TongFang.Key.TAB] = LedId.Keyboard_Tab,
            [TongFang.Key.CAPS_LOCK] = LedId.Keyboard_CapsLock,
            [TongFang.Key.LEFT_SHIFT] = LedId.Keyboard_LeftShift,
            [TongFang.Key.LEFT_CONTROL] = LedId.Keyboard_LeftCtrl,
            [TongFang.Key.ONE] = LedId.Keyboard_1,
            [TongFang.Key.Q] = LedId.Keyboard_Q,
            [TongFang.Key.A] = LedId.Keyboard_A,
            [TongFang.Key.BACKSLASH_UK] = LedId.Keyboard_NonUsBackslash,
            [TongFang.Key.LEFT_WINDOWS] = LedId.Keyboard_LeftGui,
            [TongFang.Key.F1] = LedId.Keyboard_F1,
            [TongFang.Key.TWO] = LedId.Keyboard_2,
            [TongFang.Key.W] = LedId.Keyboard_W,
            [TongFang.Key.S] = LedId.Keyboard_S,
            [TongFang.Key.Z] = LedId.Keyboard_Z,
            [TongFang.Key.LEFT_ALT] = LedId.Keyboard_LeftAlt,
            [TongFang.Key.F2] = LedId.Keyboard_F2,
            [TongFang.Key.THREE] = LedId.Keyboard_3,
            [TongFang.Key.E] = LedId.Keyboard_E,
            [TongFang.Key.D] = LedId.Keyboard_D,
            [TongFang.Key.X] = LedId.Keyboard_X,
            [TongFang.Key.F3] = LedId.Keyboard_F3,
            [TongFang.Key.FOUR] = LedId.Keyboard_4,
            [TongFang.Key.R] = LedId.Keyboard_R,
            [TongFang.Key.F] = LedId.Keyboard_F,
            [TongFang.Key.C] = LedId.Keyboard_C,
            [TongFang.Key.F4] = LedId.Keyboard_F4,
            [TongFang.Key.FIVE] = LedId.Keyboard_5,
            [TongFang.Key.T] = LedId.Keyboard_T,
            [TongFang.Key.G] = LedId.Keyboard_G,
            [TongFang.Key.V] = LedId.Keyboard_V,
            [TongFang.Key.SIX] = LedId.Keyboard_6,
            [TongFang.Key.Y] = LedId.Keyboard_Y,
            [TongFang.Key.H] = LedId.Keyboard_H,
            [TongFang.Key.B] = LedId.Keyboard_B,
            [TongFang.Key.SPACE] = LedId.Keyboard_Space,
            [TongFang.Key.F5] = LedId.Keyboard_F5,
            [TongFang.Key.SEVEN] = LedId.Keyboard_7,
            [TongFang.Key.U] = LedId.Keyboard_U,
            [TongFang.Key.J] = LedId.Keyboard_J,
            [TongFang.Key.N] = LedId.Keyboard_N,
            [TongFang.Key.F6] = LedId.Keyboard_F6,
            [TongFang.Key.EIGHT] = LedId.Keyboard_8,
            [TongFang.Key.I] = LedId.Keyboard_I,
            [TongFang.Key.K] = LedId.Keyboard_K,
            [TongFang.Key.M] = LedId.Keyboard_M,
            [TongFang.Key.F7] = LedId.Keyboard_F7,
            [TongFang.Key.NINE] = LedId.Keyboard_9,
            [TongFang.Key.O] = LedId.Keyboard_O,
            [TongFang.Key.L] = LedId.Keyboard_L,
            [TongFang.Key.COMMA] = LedId.Keyboard_CommaAndLessThan,
            [TongFang.Key.F8] = LedId.Keyboard_F8,
            [TongFang.Key.ZERO] = LedId.Keyboard_0,
            [TongFang.Key.P] = LedId.Keyboard_P,
            [TongFang.Key.SEMICOLON] = LedId.Keyboard_SemicolonAndColon,
            [TongFang.Key.PERIOD] = LedId.Keyboard_PeriodAndBiggerThan,
            [TongFang.Key.RIGHT_ALT] = LedId.Keyboard_RightAlt,
            [TongFang.Key.MINUS] = LedId.Keyboard_MinusAndUnderscore,
            [TongFang.Key.OPEN_BRACKET] = LedId.Keyboard_BracketLeft,
            [TongFang.Key.APOSTROPHE] = LedId.Keyboard_ApostropheAndDoubleQuote,
            [TongFang.Key.FORWARD_SLASH] = LedId.Keyboard_SlashAndQuestionMark,
            [TongFang.Key.FN_Key] = LedId.Keyboard_Function,
            [TongFang.Key.F9] = LedId.Keyboard_F9,
            [TongFang.Key.EQUALS] = LedId.Keyboard_EqualsAndPlus,
            [TongFang.Key.CLOSE_BRACKET] = LedId.Keyboard_BracketRight,
            [TongFang.Key.BACKSLASH] = LedId.Keyboard_Backslash,
            [TongFang.Key.RIGHT_SHIFT] = LedId.Keyboard_RightShift,
            [TongFang.Key.MENU] = LedId.Keyboard_Application,
            [TongFang.Key.F10] = LedId.Keyboard_F10,
            [TongFang.Key.F11] = LedId.Keyboard_F11,
            [TongFang.Key.F12] = LedId.Keyboard_F12,
            [TongFang.Key.BACKSPACE] = LedId.Keyboard_Backspace,
            [TongFang.Key.ENTER] = LedId.Keyboard_Enter,
            [TongFang.Key.RIGHT_CONTROL] = LedId.Keyboard_RightCtrl,
            [TongFang.Key.HASHTAG] = LedId.Keyboard_NonUsTilde,
            [TongFang.Key.PRINT_SCREEN] = LedId.Keyboard_PrintScreen,
            [TongFang.Key.INSERT] = LedId.Keyboard_Insert,
            [TongFang.Key.DELETE] = LedId.Keyboard_Delete,
            [TongFang.Key.ARROW_LEFT] = LedId.Keyboard_ArrowLeft,
            [TongFang.Key.HOME] = LedId.Keyboard_Home,
            [TongFang.Key.END] = LedId.Keyboard_End,
            [TongFang.Key.UP_ARROW] = LedId.Keyboard_ArrowUp,
            [TongFang.Key.DOWN_ARROW] = LedId.Keyboard_ArrowDown,
            [TongFang.Key.PAGE_UP] = LedId.Keyboard_PageUp,
            [TongFang.Key.PAGE_DOWN] = LedId.Keyboard_PageDown,
            [TongFang.Key.RIGHT_ARROW] = LedId.Keyboard_ArrowRight,
            [TongFang.Key.NUMLOCK] = LedId.Keyboard_NumLock,
            [TongFang.Key.NUMPAD_SEVEN] = LedId.Keyboard_Num7,
            [TongFang.Key.NUMPAD_FOUR] = LedId.Keyboard_Num4,
            [TongFang.Key.NUMPAD_ONE] = LedId.Keyboard_Num1,
            [TongFang.Key.NUMPAD_0] = LedId.Keyboard_Num0,
            [TongFang.Key.NUMPAD_DIVIDE] = LedId.Keyboard_NumSlash,
            [TongFang.Key.NUMPAD_EIGHT] = LedId.Keyboard_Num8,
            [TongFang.Key.NUMPAD_FIVE] = LedId.Keyboard_Num5,
            [TongFang.Key.NUMPAD_TWO] = LedId.Keyboard_Num2,
            [TongFang.Key.NUMPAD_MULTIPLY] = LedId.Keyboard_NumAsterisk,
            [TongFang.Key.NUMPAD_NINE] = LedId.Keyboard_Num9,
            [TongFang.Key.NUMPAD_SIX] = LedId.Keyboard_Num6,
            [TongFang.Key.NUMPAD_THREE] = LedId.Keyboard_Num3,
            [TongFang.Key.NUMPAD_PERIOD] = LedId.Keyboard_NumPeriodAndDelete,
            [TongFang.Key.NUMPAD_MINUS] = LedId.Keyboard_NumMinus,
            [TongFang.Key.NUMPAD_PLUS] = LedId.Keyboard_NumPlus,
            [TongFang.Key.NUMPAD_ENTER] = LedId.Keyboard_NumEnter,
        };
    }
}
