using Aurora.Devices;
using System.Collections.Generic;
using TongFang;

namespace TongFangAuroraPlugin
{
    internal static class TongFangKeyMap
    {
        public static readonly Dictionary<DeviceKeys, (byte Row, byte Column)> IsoCoords = new Dictionary<DeviceKeys, (byte Row, byte Column)>
        {
            [DeviceKeys.LEFT_CONTROL] = (0, 0),
            [DeviceKeys.FN_Key] = (0, 2),
            [DeviceKeys.LEFT_WINDOWS] = (0, 3),
            [DeviceKeys.LEFT_ALT] = (0, 4),
            [DeviceKeys.SPACE] = (0, 7),
            [DeviceKeys.RIGHT_ALT] = (0, 10),
            [DeviceKeys.APPLICATION_SELECT] = (0, 11),
            [DeviceKeys.RIGHT_CONTROL] = (0, 12),
            [DeviceKeys.ARROW_LEFT] = (0, 13),
            [DeviceKeys.ARROW_DOWN] = (0, 14),
            [DeviceKeys.ARROW_RIGHT] = (0, 15),
            [DeviceKeys.NUM_ZERO] = (0, 16),
            [DeviceKeys.NUM_PERIOD] = (0, 17),

            [DeviceKeys.LEFT_SHIFT] = (1, 0),
            [DeviceKeys.BACKSLASH_UK] = (1, 2),
            [DeviceKeys.Z] = (1, 3),
            [DeviceKeys.X] = (1, 4),
            [DeviceKeys.C] = (1, 5),
            [DeviceKeys.V] = (1, 6),
            [DeviceKeys.B] = (1, 7),
            [DeviceKeys.N] = (1, 8),
            [DeviceKeys.M] = (1, 9),
            [DeviceKeys.COMMA] = (1, 10),
            [DeviceKeys.PERIOD] = (1, 11),
            [DeviceKeys.FORWARD_SLASH] = (1, 12),
            [DeviceKeys.RIGHT_SHIFT] = (1, 13),
            [DeviceKeys.ARROW_UP] = (1, 14),
            [DeviceKeys.NUM_ONE] = (1, 15),
            [DeviceKeys.NUM_TWO] = (1, 16),
            [DeviceKeys.NUM_THREE] = (1, 17),
            [DeviceKeys.NUM_ENTER] = (1, 18),

            [DeviceKeys.CAPS_LOCK] = (2, 0),
            [DeviceKeys.A] = (2, 2),
            [DeviceKeys.S] = (2, 3),
            [DeviceKeys.D] = (2, 4),
            [DeviceKeys.F] = (2, 5),
            [DeviceKeys.G] = (2, 6),
            [DeviceKeys.H] = (2, 7),
            [DeviceKeys.J] = (2, 8),
            [DeviceKeys.K] = (2, 9),
            [DeviceKeys.L] = (2, 10),
            [DeviceKeys.SEMICOLON] = (2, 11),
            [DeviceKeys.APOSTROPHE] = (2, 12),
            [DeviceKeys.HASHTAG] = (2, 13),
            [DeviceKeys.NUM_FOUR] = (2, 15),
            [DeviceKeys.NUM_FIVE] = (2, 16),
            [DeviceKeys.NUM_SIX] = (2, 17),

            [DeviceKeys.TAB] = (3, 0),
            [DeviceKeys.Q] = (3, 2),
            [DeviceKeys.W] = (3, 3),
            [DeviceKeys.E] = (3, 4),
            [DeviceKeys.R] = (3, 5),
            [DeviceKeys.T] = (3, 6),
            [DeviceKeys.Y] = (3, 7),
            [DeviceKeys.U] = (3, 8),
            [DeviceKeys.I] = (3, 9),
            [DeviceKeys.O] = (3, 10),
            [DeviceKeys.P] = (3, 11),
            [DeviceKeys.OPEN_BRACKET] = (3, 12),
            [DeviceKeys.CLOSE_BRACKET] = (3, 13),
            [DeviceKeys.ENTER] = (3, 14),
            [DeviceKeys.NUM_SEVEN] = (3, 15),
            [DeviceKeys.NUM_EIGHT] = (3, 16),
            [DeviceKeys.NUM_NINE] = (3, 17),
            [DeviceKeys.NUM_PLUS] = (3, 18),

            [DeviceKeys.TILDE] = (4, 0),
            [DeviceKeys.ONE] = (4, 1),
            [DeviceKeys.TWO] = (4, 2),
            [DeviceKeys.THREE] = (4, 3),
            [DeviceKeys.FOUR] = (4, 4),
            [DeviceKeys.FIVE] = (4, 5),
            [DeviceKeys.SIX] = (4, 6),
            [DeviceKeys.SEVEN] = (4, 7),
            [DeviceKeys.EIGHT] = (4, 8),
            [DeviceKeys.NINE] = (4, 9),
            [DeviceKeys.ZERO] = (4, 10),
            [DeviceKeys.MINUS] = (4, 11),
            [DeviceKeys.EQUALS] = (4, 12),
            [DeviceKeys.BACKSPACE] = (4, 14),
            [DeviceKeys.NUM_LOCK] = (4, 15),
            [DeviceKeys.NUM_SLASH] = (4, 16),
            [DeviceKeys.NUM_ASTERISK] = (4, 17),
            [DeviceKeys.NUM_MINUS] = (4, 18),

            [DeviceKeys.ESC] = (5, 0),
            [DeviceKeys.F1] = (5, 1),
            [DeviceKeys.F2] = (5, 2),
            [DeviceKeys.F3] = (5, 3),
            [DeviceKeys.F4] = (5, 4),
            [DeviceKeys.F5] = (5, 5),
            [DeviceKeys.F6] = (5, 6),
            [DeviceKeys.F7] = (5, 7),
            [DeviceKeys.F8] = (5, 8),
            [DeviceKeys.F9] = (5, 9),
            [DeviceKeys.F10] = (5, 10),
            [DeviceKeys.F11] = (5, 11),
            [DeviceKeys.F12] = (5, 12),
            [DeviceKeys.INSERT] = (5, 13),
            [DeviceKeys.DELETE] = (5, 14),
            [DeviceKeys.HOME] = (5, 15),
            [DeviceKeys.END] = (5, 16),
            [DeviceKeys.PAGE_UP] = (5, 17),
            [DeviceKeys.PAGE_DOWN] = (5, 18)
        };

        public static readonly Dictionary<DeviceKeys, (byte Row, byte Column)> AnsiCoords = new Dictionary<DeviceKeys, (byte Row, byte Column)>
        {
            [DeviceKeys.LEFT_CONTROL] = (0, 0),
            [DeviceKeys.FN_Key] = (0, 1),
            [DeviceKeys.LEFT_WINDOWS] = (0, 3),
            [DeviceKeys.LEFT_ALT] = (0, 4),
            [DeviceKeys.SPACE] = (0, 7),
            [DeviceKeys.RIGHT_ALT] = (0, 10),
            [DeviceKeys.APPLICATION_SELECT] = (0, 11),
            [DeviceKeys.RIGHT_CONTROL] = (0, 12),
            [DeviceKeys.ARROW_LEFT] = (0, 13),
            [DeviceKeys.ARROW_DOWN] = (0, 14),
            [DeviceKeys.ARROW_RIGHT] = (0, 15),

            [DeviceKeys.LEFT_SHIFT] = (1, 1),
            [DeviceKeys.Z] = (1, 3),
            [DeviceKeys.X] = (1, 4),
            [DeviceKeys.C] = (1, 5),
            [DeviceKeys.V] = (1, 6),
            [DeviceKeys.B] = (1, 7),
            [DeviceKeys.N] = (1, 8),
            [DeviceKeys.M] = (1, 9),
            [DeviceKeys.COMMA] = (1, 10),
            [DeviceKeys.PERIOD] = (1, 11),
            [DeviceKeys.FORWARD_SLASH] = (1, 12),
            [DeviceKeys.RIGHT_SHIFT] = (1, 13),
            [DeviceKeys.ARROW_UP] = (1, 14),
            [DeviceKeys.END] = (1, 15),

            [DeviceKeys.CAPS_LOCK] = (2, 0),
            [DeviceKeys.A] = (2, 2),
            [DeviceKeys.S] = (2, 3),
            [DeviceKeys.D] = (2, 4),
            [DeviceKeys.F] = (2, 5),
            [DeviceKeys.G] = (2, 6),
            [DeviceKeys.H] = (2, 7),
            [DeviceKeys.J] = (2, 8),
            [DeviceKeys.K] = (2, 9),
            [DeviceKeys.L] = (2, 10),
            [DeviceKeys.SEMICOLON] = (2, 11),
            [DeviceKeys.APOSTROPHE] = (2, 12),
            [DeviceKeys.ENTER] = (2, 14),
            [DeviceKeys.PAGE_DOWN] = (2, 15),

            [DeviceKeys.TAB] = (3, 0),
            [DeviceKeys.Q] = (3, 2),
            [DeviceKeys.W] = (3, 3),
            [DeviceKeys.E] = (3, 4),
            [DeviceKeys.R] = (3, 5),
            [DeviceKeys.T] = (3, 6),
            [DeviceKeys.Y] = (3, 7),
            [DeviceKeys.U] = (3, 8),
            [DeviceKeys.I] = (3, 9),
            [DeviceKeys.O] = (3, 10),
            [DeviceKeys.P] = (3, 11),
            [DeviceKeys.OPEN_BRACKET] = (3, 12),
            [DeviceKeys.CLOSE_BRACKET] = (3, 13),
            [DeviceKeys.BACKSLASH] = (3, 14),
            [DeviceKeys.PAGE_UP] = (3, 15),

            [DeviceKeys.TILDE] = (4, 0),
            [DeviceKeys.ONE] = (4, 1),
            [DeviceKeys.TWO] = (4, 2),
            [DeviceKeys.THREE] = (4, 3),
            [DeviceKeys.FOUR] = (4, 4),
            [DeviceKeys.FIVE] = (4, 5),
            [DeviceKeys.SIX] = (4, 6),
            [DeviceKeys.SEVEN] = (4, 7),
            [DeviceKeys.EIGHT] = (4, 8),
            [DeviceKeys.NINE] = (4, 9),
            [DeviceKeys.ZERO] = (4, 10),
            [DeviceKeys.MINUS] = (4, 11),
            [DeviceKeys.EQUALS] = (4, 12),
            [DeviceKeys.BACKSPACE] = (4, 14),
            [DeviceKeys.HOME] = (4, 15),

            [DeviceKeys.ESC] = (5, 0),
            [DeviceKeys.F1] = (5, 1),
            [DeviceKeys.F2] = (5, 2),
            [DeviceKeys.F3] = (5, 3),
            [DeviceKeys.F4] = (5, 4),
            [DeviceKeys.F5] = (5, 5),
            [DeviceKeys.F6] = (5, 6),
            [DeviceKeys.F7] = (5, 7),
            [DeviceKeys.F8] = (5, 8),
            [DeviceKeys.F9] = (5, 9),
            [DeviceKeys.F10] = (5, 10),
            [DeviceKeys.F11] = (5, 11),
            [DeviceKeys.F12] = (5, 12),
            [DeviceKeys.INSERT] = (5, 13),
            [DeviceKeys.PRINT_SCREEN] = (5, 14),
            [DeviceKeys.DELETE] = (5, 15),
        };

        public static readonly Dictionary<Layout, Dictionary<DeviceKeys, (byte Row, byte Column)>> Coords = new Dictionary<Layout, Dictionary<DeviceKeys, (byte Row, byte Column)>>() 
        {
            [Layout.ISO] = IsoCoords,
            [Layout.ANSI] = AnsiCoords
        };
    }
}
